//AUTHENTICATION TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//REGISTRATION TYPES
export const SET_VENUE = 'SET_VENUE';
export const SET_USER = 'SET_USER';
export const VENUE_CREATE_ERROR = 'VENUE_CREATE_ERROR';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

//PARTY TYPES
export const GET_PARTIES = 'GET_PARTIES';
export const ADD_PARTY = 'ADD_PARTY';
export const DELETE_PARTY = 'DELETE_PARTY';
export const PARTY_ERROR = 'PARTY_ERROR';
export const CLEAR_PARTIES = 'CLEAR_PARTIES';
export const SEARCH_PARTIES = 'SEARCH_PARTIES';
export const FILTER_PARTIES = 'FILTER_PARTIES';
export const CLEAR_FILTER = 'CLEAR_FILTER';

//SERVER TYPES
export const GET_SERVERS = 'GET_SERVERS';
export const REMOVE_SERVER = 'REMOVE_SERVER';
export const ADD_SERVER = 'ADD_SERVER';
export const SERVER_ERROR = 'SERVER_ERROR';
export const SET_CURRENT_SERVER = 'SET_CURRENT_SERVER';
export const UPDATE_SERVER = 'UPDATE_SERVER';

//VENUE TYPES
export const GET_VENUE = 'GET_VENUE';
export const VENUE_ERROR = 'VENUE_ERROR';

//LOADING/ERRORS
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
